title_html: Mason Nakamura
description: Undergraduate Researcher and Student
repo: https://github.com/MasonN808
email: Mason.Nakamura1@Berkeley.edu
curriculum:
    url: https://drive.google.com/file/d/1EatXBFcPfavdq_Rjz6vxxT_LopsOoaCz/view?usp=sharing
